version: '3.9'

services:
  postgres:
    container_name: postgres-container
    image: postgres:15
    env_file:
      - ./.env
    links:
      - redis
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./app/server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app/server/sql/drop_events_table.sql:/drop_events_table.sql
      - ./app/server/database/clear_events.sh:/clear_events.sh
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - local_network

  redis:
    image: redis:6.2
    container_name: redis-container
    env_file:
      - ./.env
    volumes:
      - ./app/server/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
